# Debian's ncbi-vdb package: https://salsa.debian.org/med-team/ncbi-vdb

# Paths to toolchain binaries (gcc, g++, ar) are in part hard-coded and
# need to be patched.

sed -i.backup \
    -e "s|gcc|$CC|g" \
    -e "s|g++|$CXX|g" \
    build/Makefile.gcc

# --debug prints extra debugging info while the configure script is running
# CXX appears to be the only

./configure \
    --debug \
    --prefix=$PREFIX \
    --build-prefix=ncbi-outdir \
    --with-ngs-sdk-prefix=$PREFIX \
    CXX=$CXX

# This build configuration file is generated by configure
sed -i.backup \
    -e "s|= gcc|= $CC|" \
    -e "s|= gcc|= $CXX|" \
    -e "s|= ar rc|= ar|" \
    -e "s|= ar|= $AR|" \
    build/Makefile.config.linux.x86_64

make
make install

# These tests fail sometimes because they try to access online resources
make -C test/vdb

# A 'make install' does not install header files, so copy them manually
# (this is also done by the Debian package)
mv interfaces/* $PREFIX/include/ncbi-vdb

# To Do

# Some of the internal libraries are not built. These messages are printed during the build:

# NOTE - internal library libkff cannot be built: It requires 'libmagic' and its development headers.
# NOTE - internal library libkxml cannot be built: It requires 'libxml2' and its development headers.
# NOTE - internal library libkxfs cannot be built: It requires 'libxml2' and its development headers.
# NOTE - library libkdf5 cannot be built: It requires 'libhdf5' and its development headers.
# NOTE - library libvdb-sqlite cannot be built: It requires 'libxml2'.

# These other notes are written:

# bison: command not found
# bc: command not found
