# Debian's ncbi-vdb package: https://salsa.debian.org/med-team/ncbi-vdb

# Paths to toolchain binaries (gcc, g++, ar) are in part hard-coded and
# need to be patched.

sed -i.backup \
    -e "s|gcc|$CC|g" \
    -e "s|g++|$CXX|g" \
    build/Makefile.gcc

# --debug prints extra debugging info while the configure script is running
# CXX appears to be the only

./configure \
    --debug \
    --prefix=$PREFIX \
    --build-prefix=ncbi-outdir \
    --with-ngs-sdk-prefix=$PREFIX \
    CXX=$CXX

# This build configuration file is generated by configure
sed -i.backup \
    -e "s|= gcc|= $CC|" \
    -e "s|= gcc|= $CXX|" \
    -e "s|= ar rc|= ar|" \
    -e "s|= ar|= $AR|" \
    build/Makefile.config.linux.x86_64

make
make install

# These tests fail sometimes because they try to access online resources
make -C test/vdb

# A 'make install' does not install header files, so copy them manually
# (this is also done by the Debian package)
mv interfaces/* $PREFIX/include/ncbi-vdb
